import { Roboto } from "next/font/google";
import Providers from "./components/Providers";
import { ThemeContextProvider } from "./components/ThemeContextProvider";
import TopBar from "./components/TopBar";
import { Box } from "@mui/material";

const roboto = Roboto({
  subsets: ["latin"], // Include the required subsets
  weight: ["400", "700"], // Specify font weights
  style: ["normal", "italic"], // Specify styles
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <ThemeContextProvider>
        <html lang="en">
          <body className={roboto.className}>
            <TopBar />
            <Box sx={{pt: 10}}>{children}</Box>
          </body>
        </html>
      </ThemeContextProvider>
    </Providers>
  );
}
