import { Roboto } from 'next/font/google';
import Providers from './components/Providers';

const roboto = Roboto({
  subsets: ['latin'], // Include the required subsets
  weight: ['400', '700'], // Specify font weights
  style: ['normal', 'italic'], // Specify styles
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
    <html lang="en">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
    </Providers>
  );
}
